# Start Numpy Journey --> 28 December 2024

# Create Numpy basic

In [12]:
import numpy as np

# Create 0D array

In [10]:
l0 = 7
print(type(l0))

arr = np.array(l0)
print(arr)
print(type(arr))
print(f'Array Diamension: {arr.ndim}')

<class 'int'>
7
<class 'numpy.ndarray'>
Array Diamension: 0


# Create 1D array

In [11]:
l1 = [1, 2, 3, 4, 5]
print(type(l1))

arr = np.array(l1)
print(arr)
print(type(arr))
print(f'Array Diamension: {arr.ndim}')

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
Array Diamension: 1


# Create 2D array

In [7]:
l2 = [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
    ]
print(type(l2))

arr = np.array(l2)
print(arr)
print(type(arr))
print(f'Array Diamension: {arr.ndim}')

<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
Array Diamension: 2


# Create 3D Array

In [8]:
l3 = [[
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]]

print(type(l3))

arr = np.array(l3)
print(arr)
print(type(arr))
print(f'Array Diamension: {arr.ndim}')

<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'>
Array Diamension: 3


# Create N-D Array

In [9]:
l4 = [1, 2, 3]
arr = np.array(l4, ndmin=5)
print(arr)
print(type(arr))
print(f'Array Diamension: {arr.ndim}')

[[[[[1 2 3]]]]]
<class 'numpy.ndarray'>
Array Diamension: 5
