#Search, Sort, Filter

In [2]:
import numpy as np

# 1. Linear Search

In [10]:
mtx1 = np.array([1,2,3,4,15,6,7,8,9,10]*3)
print(f"Original Matrix: {mtx1}")
print()

index = np.where(mtx1 == 15)
print(f"Index of 5: {index}")

index2 = np.where(mtx1%2 == 0)
print(f"Even Numbers index: {index2}")

Original Matrix: [ 1  2  3  4 15  6  7  8  9 10  1  2  3  4 15  6  7  8  9 10  1  2  3  4
 15  6  7  8  9 10]

Index of 5: (array([ 4, 14, 24]),)
Even Numbers index: (array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]),)


# 2. Binary Search (Sorted Search)

In [17]:
mtx2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Original Matrix: {mtx2}")
print()

index = np.searchsorted(mtx2, 6)
print(f"Index of 6: {index}")

#search by list
index2 = np.searchsorted(mtx2, [6,8,10])
print(f"Index of [6, 8, 10]: {index2}")

Original Matrix: [ 1  2  3  4  5  6  7  8  9 10]

Index of 6: 5
Index of [6, 8, 10]: [5 7 9]


#3. Sort

In [18]:
mtx3 = np.array([1,12,3,41,15,6,77,8,99,10])
print(f"Original Matrix: {mtx3}")
print()

mtx3.sort()
print(f"Sorted Matrix: {mtx3}")

Original Matrix: [ 1 12  3 41 15  6 77  8 99 10]

Sorted Matrix: [ 1  3  6  8 10 12 15 41 77 99]


In [20]:
mtx4 = np.array([
                  [1,12,3],
                  [41,15,6],
                  [77,8,99],
                  [11,12,10]
                 ])
print(f"Original Matrix: \n{mtx4}")
print()

mtx4.sort()
print(f"Sorted Matrix: \n{mtx4}")

Original Matrix: 
[[ 1 12  3]
 [41 15  6]
 [77  8 99]
 [11 12 10]]

Sorted Matrix: 
[[ 1  3 12]
 [ 6 15 41]
 [ 8 77 99]
 [10 11 12]]


In [23]:
#String sort
mtx5 = np.array(['mango', 'banana', 'litchi', 'cherry', 'apple'])
print(f"Original Matrix: {mtx5}")
print()

mtx5.sort()
print(f"Sorted Matrix: {mtx5}")

Original Matrix: ['mango' 'banana' 'litchi' 'cherry' 'apple']

Sorted Matrix: ['apple' 'banana' 'cherry' 'litchi' 'mango']


#4. Filter

In [26]:
mtx6 = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Original Matrix: {mtx6}")
print()

filter = [True, False, True, False, True, False, True, False, True, False]
print(f"Filtered Matrix: {mtx6[filter]}")

Original Matrix: [ 1  2  3  4  5  6  7  8  9 10]

Filtered Matrix: [1 3 5 7 9]
