# Arithmetic Function

In [1]:
import numpy as np

# 1. Shuffle

In [3]:
mtx1 = np.arange(10)
print(f"Original Matrix: {mtx1}")

np.random.shuffle(mtx1)
print(f"Shuffled Matrix: {mtx1}")

Original Matrix: [0 1 2 3 4 5 6 7 8 9]
Shuffled Matrix: [7 4 0 2 8 1 9 6 5 3]


In [5]:
mtx2 = np.arange(9).reshape(3,3)
print(f"Original Matrix: \n{mtx2}")

np.random.shuffle(mtx2)
print(f"\nShuffled Matrix: \n{mtx2}")

Original Matrix: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Shuffled Matrix: 
[[6 7 8]
 [0 1 2]
 [3 4 5]]


# 2. Unique

In [7]:
l = [1,2,2,3,3,3]
mtx3 = np.array(l)

print(f"Original Matrix: {mtx3}")

print(f"\nUnique Matrix: {np.unique(mtx3)}")

Original Matrix: [1 2 2 3 3 3]

Unique Matrix: [1 2 3]


In [15]:
mtx4 = np.array([
    [1, 2, 2],
    [3, 1, 5],
    [5, 1, 2],
],)
print(f"Original Matrix: \n{mtx4}")

print(f"\nUnique Matrix: {np.unique(mtx4)}")

Original Matrix: 
[[1 2 2]
 [3 1 5]
 [5 1 2]]

Unique Matrix: [1 2 3 5]


# 3. Resize

In [22]:
#Resize array and i can convert this to 2-D
mtx5 = np.array([1,2,3,4, 5, 6, 7])
print(f"Original Matrix: {mtx5}")

x = np.resize(mtx5, (4,3))
print(f"\nResized Matrix: \n{x}")
print(f"\nShape: {x.shape}")

Original Matrix: [1 2 3 4 5 6 7]

Resized Matrix: 
[[1 2 3]
 [4 5 6]
 [7 1 2]
 [3 4 5]]

Shape: (4, 3)


#4. Flatten

order:
  1. C : c-style --> row wise
  2. F : Fortan --> column wise
  3. A :
  4. K

In [32]:
# COnvert 2-D array to 1-D array
mtx6 = np.array([
    [1, 2, 2],
    [3, 1, 5],
    [5, 1, 2],
],)
print(f"Original Matrix: \n{mtx6}")

x = mtx6.flatten()
print(f"\nFlatten Matrix: {x}")

x[0] = 100
print(f"\nAfter Change values of 0's index")
print(f"Original Matrix: \n{mtx6}")
print(f"Flatten Matrix: {x}")
print()



Original Matrix: 
[[1 2 2]
 [3 1 5]
 [5 1 2]]

Flatten Matrix: [1 2 2 3 1 5 5 1 2]

After Change values of 0's index
Original Matrix: 
[[1 2 2]
 [3 1 5]
 [5 1 2]]
Flatten Matrix: [100   2   2   3   1   5   5   1   2]



In [37]:
# Play with order
print(f"Original Matrix: \n{mtx6}")

v = mtx6.flatten(order='C')
print(f"\nFlatten Matrix - C: {v}")

x = mtx6.flatten(order='F')
print(f"\nFlatten Matrix - F: {x}")

y = mtx6.flatten(order='A')
print(f"\nFlatten Matrix - A: {y}")

z = mtx6.flatten(order='K')
print(f"\nFlatten Matrix - K: {z}")

Original Matrix: 
[[1 2 2]
 [3 1 5]
 [5 1 2]]

Flatten Matrix - C: [1 2 2 3 1 5 5 1 2]

Flatten Matrix - F: [1 3 5 2 1 1 2 5 2]

Flatten Matrix - A: [1 2 2 3 1 5 5 1 2]

Flatten Matrix - K: [1 2 2 3 1 5 5 1 2]


#5. Ravel

In [31]:
# COnvert 2-D array to 1-D array
mtx7 = np.array([
    [1, 2, 2],
    [3, 1, 5],
    [5, 1, 2],
],)
print(f"Original Matrix: \n{mtx7}")

x = np.ravel(mtx7)
print(f"\nFlatten Matrix: {x}")

x[0] = 100 #Ravel is same like pass by reference, change original value
print(f"\nAfter Change values of 0's index")
print(f"Original Matrix: \n{mtx7}")
print(f"Flatten Matrix: {x}")

Original Matrix: 
[[1 2 2]
 [3 1 5]
 [5 1 2]]

Flatten Matrix: [1 2 2 3 1 5 5 1 2]

After Change values of 0's index
Original Matrix: 
[[100   2   2]
 [  3   1   5]
 [  5   1   2]]
Flatten Matrix: [100   2   2   3   1   5   5   1   2]


In [36]:
# Order practice
print(f"Original Matrix: \n{mtx7}")

z = np.ravel(mtx7, order='C')
print(f"\nFlatten Matrix - C: {z}")

x = np.ravel(mtx7, order='F')
print(f"\nFlatten Matrix - F: {x}")

t = np.ravel(mtx7, order='A')
print(f"\nFlatten Matrix - A: {t}")

y = np.ravel(mtx7, order='K')
print(f"\nFlatten Matrix - K: {y}")
#

Original Matrix: 
[[100   2   2]
 [  3   1   5]
 [  5   1   2]]

Flatten Matrix: [100   2   2   3   1   5   5   1   2]

Flatten Matrix: [100   3   5   2   1   1   2   5   2]

Flatten Matrix: [100   2   2   3   1   5   5   1   2]

Flatten Matrix: [100   2   2   3   1   5   5   1   2]
