# insert, append, delete

In [1]:
import numpy as np

In [2]:
mtx1 = np.array([1,2,3,4,5,6,7,8,9])
mtx2 = np.array([
        [1,2,3],
        [4,5,6],
        [7, 8, 9],
    ])

# 1. Insert

In [11]:
x = mtx1.copy()
print(f"Before insert: {x}")
print("Shape: ", x.shape)
print()

y = np.insert(x, 0, 19.5)
print(y)
print("Shape: ", y.shape)
print()

Before insert: [1 2 3 4 5 6 7 8 9]
Shape:  (9,)

[19  1  2  3  4  5  6  7  8  9]
Shape:  (10,)



In [18]:
# 2-D array
x = mtx2.copy()
print(f"Before insert: \n{x}")
print("Shape: ", x.shape)
print()

y = np.insert(x, 0, [11, 21, 31], axis=0) #0 --> add row
print(y)
print("Shape: ", y.shape)
print()

z = np.insert(x, 0, [11, 21, 31], axis=1) #1 --> add column
print(z)
print("Shape: ", z.shape)
print()

Before insert: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)

[[11 21 31]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
Shape:  (4, 3)

[[11  1  2  3]
 [21  4  5  6]
 [31  7  8  9]]
Shape:  (3, 4)



# 2. Append

In [21]:
x = mtx1.copy()
print(f"Before append: {x}")
print("Shape: ", x.shape)
print(f"Type: {type(x)}, Dimension: {x.ndim}")
print()

y = np.append(x, 19.5)
print(y)
print("Shape: ", y.shape)
print(f"Type: {type(y)}, Dimension: {y.ndim}")
print()

Before append: [1 2 3 4 5 6 7 8 9]
Shape:  (9,)
Type: <class 'numpy.ndarray'>, Dimension: 1

[ 1.   2.   3.   4.   5.   6.   7.   8.   9.  19.5]
Shape:  (10,)
Type: <class 'numpy.ndarray'>, Dimension: 1



In [23]:
# 2-D array append
x = mtx2.copy()
print(f"Before append: \n{x}")
print("Shape: ", x.shape)
print(f"Type: {type(x)}, Dimension: {x.ndim}")
print()

y = np.append(x, [[11, 21, 31]], axis=0) #0 --> add row
print(y)
print("Shape: ", y.shape)
print(f"Type: {type(y)}, Dimension: {y.ndim}")
print()

z = np.append(x, [[11], [21], [31]], axis=1) #1 --> add column
print(z)
print("Shape: ", z.shape)


Before append: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Type: <class 'numpy.ndarray'>, Dimension: 2

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 21 31]]
Shape:  (4, 3)
Type: <class 'numpy.ndarray'>, Dimension: 2

[[ 1  2  3 11]
 [ 4  5  6 21]
 [ 7  8  9 31]]
Shape:  (3, 4)


# 3 Delete

In [25]:
x = mtx1.copy()
print(f"Before delete: {x}")
print("Shape: ", x.shape)
print()

y = np.delete(x, 0) # --> delete data from index 0
print(y)
print("Shape: ", y.shape)
print()
#

Before delete: [1 2 3 4 5 6 7 8 9]
Shape:  (9,)

[2 3 4 5 6 7 8 9]
Shape:  (8,)



In [26]:
# 2D array data delete using delete function
x = mtx2.copy()
print(f"Before delete: \n{x}")
print("Shape: ", x.shape)
print()

y = np.delete(x, 0, axis=0) #0 --> delete row
print(y)
print("Shape: ", y.shape)
print()

z = np.delete(x, 0, axis=1) #1 --> delete column
print(z)
print("Shape: ", z.shape)
print()

Before delete: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)

[[4 5 6]
 [7 8 9]]
Shape:  (2, 3)

[[2 3]
 [5 6]
 [8 9]]
Shape:  (3, 2)

