# Matrix

In [1]:
import numpy as np

In [7]:
arr1 = np.array([
        [5,6,7],
        [8,9,10],
        [11,12,13]
    ])

arr2 = np.array([
        [1,2,3],
        [3,2,1],
        [3,2,1]
    ])


In [10]:
mtx1 = np.matrix([
        [5,6,7],
        [8,9,10],
        [11,12,13]
    ])

mtx2 = np.matrix([
        [1,2,3],
        [3,2,1],
        [3,2,1]
    ])

#difference between array and matrix

#1. Matrix

In [14]:
a =mtx1.copy()
b = mtx2.copy()

print(f"Matrix A: \n{a}")
print(f"Matrix B: \n{b}")
print()

# Matrix addition
c = a + b
print(f"Matrix Addition: \n{c}")
print()

# Matrix subtraction
d = a - b
print(f"Matrix Subtraction: \n{d}")
print()

# Matrix dot productu


e = a * b
print(f"Matrix Dot Product: \n{e}")
print()

print(f"Type {type(c)}, Dimension: {  d.shape  }")
print(f"Type {type(e)}, Dimension: {  e.shape  }")

Matrix A: 
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
Matrix B: 
[[1 2 3]
 [3 2 1]
 [3 2 1]]

Matrix Addition: 
[[ 6  8 10]
 [11 11 11]
 [14 14 14]]

Matrix Subtraction: 
[[ 4  4  4]
 [ 5  7  9]
 [ 8 10 12]]

Matrix Dot Product: 
[[44 36 28]
 [65 54 43]
 [86 72 58]]

Type <class 'numpy.matrix'>, Dimension: (3, 3)
Type <class 'numpy.matrix'>, Dimension: (3, 3)


In [15]:
a = arr1.copy()
b = arr2.copy()

print(f"Array A: \n{a}")
print(f"Array B: \n{b}")
print()

# Matrix addition
c = a + b
print(f"Array Addition: \n{c}")
print()

# Matrix subtraction
d = a - b
print(f"Array Subtraction: \n{d}")
print()

# matrix dot product
e = a * b
print(f"Array Dot Product: \n{e}")
print()

print(f"Type {type(c)}, Dimension: {  d.shape  }")
print(f"Type {type(e)}, Dimension: {  e.shape  }")

Array A: 
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
Array B: 
[[1 2 3]
 [3 2 1]
 [3 2 1]]

Array Addition: 
[[ 6  8 10]
 [11 11 11]
 [14 14 14]]

Array Subtraction: 
[[ 4  4  4]
 [ 5  7  9]
 [ 8 10 12]]

Array Dot Product: 
[[ 5 12 21]
 [24 18 10]
 [33 24 13]]

Type <class 'numpy.ndarray'>, Dimension: (3, 3)
Type <class 'numpy.ndarray'>, Dimension: (3, 3)


In [22]:
x = mtx1.copy()
y = mtx2.copy()
y = np.delete(y, 1, axis=1)


print(f"Original Array A: \n{x}")
print(f"\nOriginal Array B: \n{y}")

print(f"Dimension A: {x.shape}")
print(f"Dimension B: {y.shape}")
print()

# Matrix Multiplication
z = np.dot(x, y)
print(f"Matrix Multiplication: \n{z}")
print()


Original Array A: 
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

Original Array B: 
[[1 3]
 [3 1]
 [3 1]]
Dimension A: (3, 3)
Dimension B: (3, 2)

Matrix Multiplication: 
[[44 28]
 [65 43]
 [86 58]]



# 2. Transpose

In [27]:
x = np.matrix([
    [11,12,13],
    [21, 22, 23],
])
print(f"Original Array: \n{x}")
print(f"Dimension: {x.shape}")

# transpose
x = np.transpose(x)
print(f"\nTranspose Array: \n{x}")
print(f"Dimension: {x.shape}")

# Another way
x = x.T
print(f"\nTranspose Array: \n{x}")
print(f"Dimension: {x.shape}")

Original Array: 
[[11 12 13]
 [21 22 23]]
Dimension: (2, 3)

Transpose Array: 
[[11 21]
 [12 22]
 [13 23]]
Dimension: (3, 2)

Transpose Array: 
[[11 12 13]
 [21 22 23]]
Dimension: (2, 3)


# 3. Swap axes

In [29]:
x = np.matrix([
    [11,12,13],
    [21, 22, 23],
])
print(f"Original Array: \n{x}")
print(f"Dimension: {x.shape}")
print()

x = np.swapaxes(x, 0, 1)
print(f"Swap Axes Array: \n{x}")
print(f"Dimension: {x.shape}")

Original Array: 
[[11 12 13]
 [21 22 23]]
Dimension: (2, 3)

Swap Axes Array: 
[[11 21]
 [12 22]
 [13 23]]
Dimension: (3, 2)


# 4. Inverse

In [30]:
x = np.matrix([
    [1,2],
    [3,4]
])
print(f"Original Array: \n{x}")
print(f"Dimension: {x.shape}")
print()

x = np.linalg.inv(x)
print(f"Inverse Array: \n{x}")

Original Array: 
[[1 2]
 [3 4]]
Dimension: (2, 2)

Inverse Array: 
[[-2.   1. ]
 [ 1.5 -0.5]]


#5. Power

A<sup>n</sup> <br/>
Case 1:  n > 0 --> A has Normal Power <br/>
Case 2: n==0 --> A is Identity matrix<br/>
Case 3: n < 0 --> A has power and multiply with A's Inverse matrix<br/>

In [34]:


x = np.matrix([
    [1,2],
    [3,4]
])
print(f"Original Array: \n{x}")
print(f"Dimension: {x.shape}")
print()

k = np.linalg.matrix_power(x, 3)
print(f"Power of 3: \n{k}")
print()

l = np.linalg.matrix_power(x, -1)
print(f"Power of -1: \n{l}")
print()

m = np.linalg.matrix_power(x, 0)
print(f"Power of 0: \n{m}")
print()

Original Array: 
[[1 2]
 [3 4]]
Dimension: (2, 2)

Power of 3: 
[[ 37  54]
 [ 81 118]]

Power of -1: 
[[-2.   1. ]
 [ 1.5 -0.5]]

Power of 0: 
[[1 0]
 [0 1]]



# 6. Determinate of matrix

In [37]:
x = np.matrix([
    [1,2,],
    [3,4,]
])
print(f"Original Array: \n{x}")
print(f"Dimension: {x.shape}")
print()

k = np.linalg.det(x)
print(f"Determinate: \n{k}")
print()

Original Array: 
[[1 2]
 [3 4]]
Dimension: (2, 2)

Determinate: 
-2.0000000000000004

