# Some Special array

In [1]:
import numpy as np

# 1. Array filled with 0

In [4]:
arr1 = np.zeros((3, 3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 2. Array filled with 1

In [5]:
arr2 = np.ones((3, 3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 3. create empty array

In [12]:
arr3 = np.empty((2, 3, 3))
print(arr3)

[[[4.94641128e-310 0.00000000e+000 3.86144870e+156]
  [7.50009465e-312 5.67112585e-302 1.33360466e+241]
  [1.94718578e-309 1.79043022e-280 9.09929080e-307]]

 [[1.33360295e+241 5.29353070e-310 1.65847958e+166]
  [5.54041819e+228 6.75635367e-312 5.56268466e-309]
  [7.16985256e-299 1.45859711e-303 1.13888877e-303]]]


# 4. Array with range

In [18]:
arr4 = np.arange(1, 11)
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10]


# 5. Array with diagonal elements 1

In [19]:
arr5 = np.eye(4)
print(arr5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 6. Create with value with specific interval

In [24]:
arr6 = np.linspace(0, 20, num=5);
print(arr6)

[ 0.  5. 10. 15. 20.]
