# Random Number Generate and filled with matris

In [9]:
#Random Number
print(np.random.rand()) #0 -> 1
print(np.random.randn())  # negggave -> 0
print(np.random.ranf()) #0.0 -> 0.99n9
print(np.random.randint(1, 10)) # int between min -> max


0.3348891374816416
0.8056427666760935
0.873846398462726
2


In [1]:
import numpy as np

# 1. Rand() --> Number between 0-1

In [3]:
mtx1 = np.random.rand(3, 3)
print(mtx1)

[[0.96093233 0.7023174  0.55864266]
 [0.90343454 0.2731945  0.32041138]
 [0.12340074 0.7341152  0.67951715]]


# 2. Randn --> negative and close to zero

In [10]:
mtx2 = np.random.randn(3, 3)
print(mtx2)


[[-1.24728589  1.48102726 -0.43005373]
 [ 0.57197413 -0.47826816 -0.36127339]
 [-1.1006132  -0.67174515  0.94693201]]


# 3. Ranf() --> 0.00 - 0.9n9

In [11]:
mtx3 = np.random.ranf((3, 3))
print(mtx3)

[[0.98639669 0.62317289 0.2417707 ]
 [0.74618318 0.32360741 0.7645092 ]
 [0.91590146 0.63929149 0.12417747]]


# 4. Randint() --> min, max, array

In [12]:
mtx4 = np.random.randint(1, 10, (3, 3))
print(mtx4)

[[1 5 8]
 [6 9 1]
 [4 1 3]]
