# Data type in numpy same as c/c++

In [1]:
import numpy as np

In [3]:
mtx1 = np.array([1,2,3,4,5,6], dtype=np.int8)
print(mtx1)
print(type(mtx1))
print(mtx1.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int8


# conversion of between data type

In [8]:
mtx2 = np.array([1,2,3,4,5,6], dtype=np.int32)
print(mtx2)
print(type(mtx2))
print(mtx2.dtype)

print("\nConvert INT to FLOAT")
mtx3 = mtx2.astype(np.float32)
print(mtx3)
print(type(mtx3))
print(mtx3.dtype)

print("\nConvert FLOAT to INT")
mtx4 = np.int32(mtx3)
print(mtx4)
print(type(mtx4))
print(mtx4.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32

Convert INT to FLOAT
[1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>
float32

Convert FLOAT to INT
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32
