# Shape and reshape of an  array

In [1]:
import numpy as np

# 1. Shape

In [3]:
mtx1 = np.array([
      [1,2,3],
      [4,5,6]
    ])

print(mtx1)
print(type(mtx1))
print("Dimaension of an array: ", mtx1.ndim)
print("Shape of an array: ", mtx1.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Dimaension of an array:  2
Shape of an array:  (2, 3)


# multi diamension

In [4]:
mtx2 = np.array([1, 2, 3], ndmin = 5)
print(mtx2)
print(type(mtx2))
print("Dimaension of an array: ", mtx2.ndim)
print("Shape of an array: ", mtx2.shape)

[[[[[1 2 3]]]]]
<class 'numpy.ndarray'>
Dimaension of an array:  5
Shape of an array:  (1, 1, 1, 1, 3)


# 2. Reshape

# 2.1 One -> Two

In [6]:
mtx3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(mtx3)
print(type(mtx3))
print("Dimaension of an array: ", mtx3.ndim)
print("Shape of an array: ", mtx3.shape)

print()

#Reshape
mtx3 = mtx3.reshape(4, 3)
print(mtx3)
print(type(mtx3))
print("Dimaension of an array: ", mtx3.ndim)
print("Shape of an array: ", mtx3.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
Dimaension of an array:  1
Shape of an array:  (12,)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
Dimaension of an array:  2
Shape of an array:  (4, 3)


# 2.2 One --> Three

In [10]:
mtx4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(mtx4)
print(type(mtx4))
print("Dimaension of an array: ", mtx4.ndim)
print("Shape of an array: ", mtx4.shape)

print()

#Reshape
mtx4 = mtx4.reshape(2, 3, 2)
print(mtx4)
print(type(mtx4))
print("Dimaension of an array: ", mtx4.ndim)
print("Shape of an array: ", mtx4.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
Dimaension of an array:  1
Shape of an array:  (12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
<class 'numpy.ndarray'>
Dimaension of an array:  3
Shape of an array:  (2, 3, 2)


# 2.3 Three --> One

In [12]:
mtx5 = mtx4.copy();
print(f"Before reshape: {mtx5}")
print(type(mtx5))
print("Dimaension of an array: ", mtx5.ndim)
print("Shape of an array: ", mtx5.shape)

print()

mtx5 = mtx5.reshape(-1)
print(f"After reshape: {mtx5}")
print(type(mtx5))
print("Dimaension of an array: ", mtx5.ndim)
print("Shape of an array: ", mtx5.shape)

Before reshape: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
<class 'numpy.ndarray'>
Dimaension of an array:  3
Shape of an array:  (2, 3, 2)

After reshape: [ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
Dimaension of an array:  1
Shape of an array:  (12,)
