# Arithmetic Operations

In [1]:
import numpy as np

# 1. 1-D array

# Add, Sub, Mul, Div, Mod, Power, Reciprocal

In [8]:
mtx1 = np.array([1,2,3,4,5])
print(f"Original 1-D Array: {mtx1}")

# sum = mtx1 + 5
# i can use function instead od operators
add = np.add(mtx1, 5)
print(f"After addition: {add}")

sub = np.subtract(mtx1, 5)
print(f"After subtraction: {sub}")

mul = np.multiply(mtx1, 5)
print(f"After multiplication: {mul}")

div = np.divide(mtx1, 5)
print(f"After division: {div}")

mod = np.mod(mtx1, 5)
print(f"After modulus: {mod}")

power = np.power(mtx1, 2)
print(f"After power: {power}")

reciprocal = np.reciprocal(mtx1)
print(f"After reciprocal: {reciprocal}")

Original 1-D Array: [1 2 3 4 5]
After addition: [ 6  7  8  9 10]
After subtraction: [-4 -3 -2 -1  0]
After multiplication: [ 5 10 15 20 25]
After division: [0.2 0.4 0.6 0.8 1. ]
After modulus: [1 2 3 4 0]
After power: [ 1  4  9 16 25]
After reciprocal: [1 0 0 0 0]


# Operation with another 1-D matrix

In [11]:
mat2 = np.array([10,20,30,40,50])
mat3 = np.array([1,2,3,4,5])
print(f"Original 1st 1-D Array: {mat2}")
print(f"Original 2nd 1-D Array: {mat3}")

add = np.add(mat2, mat3)
print(f"After addition: {add}")

sub = np.subtract(mat2, mat3)
print(f"After subtraction: {sub}")

mul = np.multiply(mat2, mat3)
print(f"After multiplication: {mul}")

div = np.divide(mat2, mat3)
print(f"After division: {div}")

mod = np.mod(mat2, mat3)
print(f"After modulus: {mod}")

Original 1st 1-D Array: [10 20 30 40 50]
Original 2nd 1-D Array: [1 2 3 4 5]
After addition: [11 22 33 44 55]
After subtraction: [ 9 18 27 36 45]
After multiplication: [ 10  40  90 160 250]
After division: [10. 10. 10. 10. 10.]
After modulus: [0 0 0 0 0]


# 2-D Array operation

In [13]:
mtx1 = np.array([
          [1,2,3],
          [4,5,6],
          [7,8,9]
      ])
mtx2 = np.array([
        [10,20,30],
        [40,50,60],
        [70,80,90]
    ])
print(f"Original 1st 2-D Array: \n{mtx1}")
print(f"Original 2nd 2-D Array: \n{mtx2}")

add = np.add(mtx1, mtx2)
print(f"\nAfter addition: \n{add}")

sub = np.subtract(mtx1, mtx2)
print(f"After subtraction: \n{sub}")

mul = np.multiply(mtx1, mtx2)
print(f"After multiplication: \n{mul}")

div = np.divide(mtx1, mtx2)
print(f"After division: \n{div}")

mod = np.mod(mtx1, mtx2)
print(f"After modulus: \n{mod}")



Original 1st 2-D Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Original 2nd 2-D Array: 
[[10 20 30]
 [40 50 60]
 [70 80 90]]

After addition: 
[[11 22 33]
 [44 55 66]
 [77 88 99]]
After subtraction: 
[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]
After multiplication: 
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
After division: 
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
After modulus: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 1-D min, max, argmin, argmax

In [15]:
mtx3 = np.array([10,20,30,40,50, 5, 1, 90])
print(f"Original 1-D Array: {mtx3}")

min = np.min(mtx3)
minIndex = np.argmin(mtx3)
print(f"Minimum value: {min} and Min index: {minIndex}")

max = np.max(mtx3)
maxIndex = np.argmax(mtx3)
print(f"Maximum value: {max} and Max index: {maxIndex}")

Original 1-D Array: [10 20 30 40 50  5  1 90]
Minimum value: 1 and Min index: 6
Maximum value: 90 and Max index: 7


# 2-D min, max, argmin, argmax, sqrt

In [23]:
mtx4 = np.array([
        [70,20,90],
        [40,80,60],
        [10,50,30]
    ])
print(f"Original 2-D Array: \n{mtx4}")

min = np.min(mtx4)
max = np.max(mtx4)
minIndex = np.argmin(mtx4)
maxIndex = np.argmax(mtx4)

print(f"Minimum value: {min} and Min index: {minIndex}")
print(f"Maximum value: {max} and Max index: {maxIndex}")


#find row and columnwise max,  mmin value
min_row = np.min(mtx4, axis=1)
max_row = np.max(mtx4, axis=1)

print(f"\nRow wise minimum value: {min_row}")
print(f"Row wise maximum value: {max_row}")

min_col = np.min(mtx4, axis=0)
max_col = np.max(mtx4, axis=0)

print(f"\nColumn wise minimum value: {min_col}")
print(f"Column wise maximum value: {max_col}")

print("\nSquare root of each element: ")
print(np.sqrt(mtx4))

Original 2-D Array: 
[[70 20 90]
 [40 80 60]
 [10 50 30]]
Minimum value: 10 and Min index: 6
Maximum value: 90 and Max index: 2

Row wise minimum value: [20 40 10]
Row wise maximum value: [90 80 50]

Column wise minimum value: [10 20 30]
Column wise maximum value: [70 80 90]

Square root of each element: 
[[8.36660027 4.47213595 9.48683298]
 [6.32455532 8.94427191 7.74596669]
 [3.16227766 7.07106781 5.47722558]]


# sin. cos, cumsum

In [25]:
mtx5 = [1, 2, 3, 4, 5]
print(f"Original 1-D Array: {mtx5}")

sin = np.sin(mtx5)
print(f"Sin value: {sin}")

cos = np.cos(mtx5)
print(f"Cos value: {cos}")

cumsum = np.cumsum(mtx5)
print(f"Cumulative sum: {cumsum}")

Original 1-D Array: [1, 2, 3, 4, 5]
Sin value: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos value: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Cumulative sum: [ 1  3  6 10 15]


# Brodcasting

In [31]:
#Condition
# 1. There will be same dimenson
# 2. (m1 x n1) and (m2 x n2) at least one of this((n1, n2) or (m1, m2)) will be 1 and another will same

mtx6 = np.array([
    [1, 2, 3],
])

print(f"Original 2-D Array: \n{mtx6}\nShape: {mtx6.shape}")

mtx7 = np.array([
    [10],
    [20],
    [30]
])

print(f"\nOriginal 2-D Array: \n{mtx7}\nShape: {mtx7.shape}")

add = mtx6 + mtx7
print(f"\nAfter addition: \n{add}\nShape: {add.shape}")


Original 2-D Array: 
[[1 2 3]]
Shape: (1, 3)

Original 2-D Array: 
[[10]
 [20]
 [30]]
Shape: (3, 1)

After addition: 
[[11 12 13]
 [21 22 23]
 [31 32 33]]
Shape: (3, 3)


# END