# Indexing and Slicing

In [1]:
import numpy as np


# Indexing

# 1. 1-D array

In [14]:
mtx1 = np.array([10,20,30,40,50])
print(mtx1);
print(f"Index access: 2 -> {mtx1[2]}")
print(f"Index access: 3 -> {mtx1[3]}")
print(f"Index access: -1 -> {mtx1[-1]}")


[10 20 30 40 50]
Index access: 2 -> 30
Index access: 3 -> 40
Index access: -1 -> 50


#2. 2-D Array indexing

In [9]:
mtx2 = np.array([
        [10, 20, 30],
        [30, 40, 50],
        [70, 80, 90],
])

print(mtx2)
print(f"Index access: 0, 0 -> {mtx2[0, 0]}")
print(f"Index access: 1, 1 -> {mtx2[1, 1]}")
print(f"Index access: 2, 2 -> {mtx2[2, 2]}")



[[10 20 30]
 [30 40 50]
 [70 80 90]]
Index access: 0, 0 -> 10
Index access: 1, 1 -> 40
Index access: 2, 2 -> 90


# 3. 3-D Array

In [12]:
mtx3 = np.array([
    [
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90],
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [5, 7, 9],
        [11, 13, 15],
        [17, 19, 21]
    ]
])

print(mtx3)
print(f"\nIndex access: 0, 0, 0 -> {mtx3[0, 0, 0]}")
print(f"Index access: 1, 1, 1 -> {mtx3[1, 1, 1]}")
print(f"Index access: 2, 2, 2 -> {mtx3[2, 2, 2]}")

[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 5  7  9]
  [11 13 15]
  [17 19 21]]]

Index access: 0, 0, 0 -> 10
Index access: 1, 1, 1 -> 5
Index access: 2, 2, 2 -> 21


#Slicing

#1D array

In [15]:
mtx4 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(mtx4)
print(f"Slicing: 1:4 -> {mtx4[1:4]}")

[10 20 30 40 50 60 70 80 90]
Slicing: 1:4 -> [20 30 40]


# 2D array

In [19]:
mtx5 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(mtx5)
print(f"Slicing: 1:3 -> {mtx5[0, 1:3]}")
print(f"Slicing: 1:3 -> {mtx5[1, :2]}")
print(f"Slicing: 1:3 -> {mtx5[2, 1:2]}")

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Slicing: 1:3 -> [20 30]
Slicing: 1:3 -> [40 50]
Slicing: 1:3 -> [80]
