#Iteration in python

In [1]:
import numpy as np

# 1. 1-D aray

In [3]:
mtx1 = np.array([1,2,3,4,5])
print(mtx1)
print(type(mtx1), mtx1.dtype, mtx1.shape)

for i in mtx1:
  print(i)

[1 2 3 4 5]
<class 'numpy.ndarray'> int64 (5,)
1
2
3
4
5


# 2. 2D array

In [4]:
mtx2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(mtx2)
print(type(mtx2), mtx2.dtype, mtx2.shape)

for i in mtx2:
  for j in i:
    print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'> int64 (2, 5)
1
2
3
4
5
6
7
8
9
10


# 3. 3D matrix iteration

In [5]:
mtx3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
    ],
],)

print(mtx3)
print(type(mtx3), mtx3.dtype, mtx3.shape)

for i in mtx3:
  for j in i:
    for k in j:
      print(k)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'> int64 (2, 3, 3)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


# 4. nditer

In [8]:
mtx4 = np.copy(mtx3)
print(mtx4)
print(type(mtx4), mtx4.dtype, mtx4.shape)
print()

for i in np.nditer(mtx4):
  print(i)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'> int64 (2, 3, 3)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


# 5. ndenumerate

In [11]:
mtx5 = np.copy(mtx3)
print(mtx5)
print(type(mtx5), mtx5.dtype, mtx5.shape)
print()

print("(Indexes) ---> Data")
for i, val in np.ndenumerate(mtx5):
  print(i, " ---> ", val)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'> int64 (2, 3, 3)

(Indexes) ---> Data
(0, 0, 0)  --->  1
(0, 0, 1)  --->  2
(0, 0, 2)  --->  3
(0, 1, 0)  --->  4
(0, 1, 1)  --->  5
(0, 1, 2)  --->  6
(0, 2, 0)  --->  7
(0, 2, 1)  --->  8
(0, 2, 2)  --->  9
(1, 0, 0)  --->  10
(1, 0, 1)  --->  11
(1, 0, 2)  --->  12
(1, 1, 0)  --->  13
(1, 1, 1)  --->  14
(1, 1, 2)  --->  15
(1, 2, 0)  --->  16
(1, 2, 1)  --->  17
(1, 2, 2)  --->  18
