# Copy, View, Join

In [2]:
import numpy as np

#1. Copy

In [6]:
mtx1 = np.array([1,2,3,4,5])
a = mtx1.copy();

a[4] = 30;

print(f"Original array: {mtx1}")
print(f"Copied array: {a}")


Original array: [1 2 3 4 5]
Copied array: [ 1  2  3  4 30]


# 2. View

In [8]:
mtx2 = np.array([1,2,3,4,5])
b = mtx2.view();

b[4] = 30;

print(f"Original array: {mtx2}") #view chnage the original array data same as pass by reference
print(f"Copied array: {b}")


Original array: [ 1  2  3  4 30]
Copied array: [ 1  2  3  4 30]


#3. Join

# 3.1 Concatenate two array

In [12]:
mtx3 = np.array([1,2,3,4,5])
mtx4 = np.array([6,7,8,9,10])

c = np.concatenate((mtx3,mtx4))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


# 3.2 2-D array concatenate

In [20]:
mtx5 = np.array([
      [1,2,3,4,5],
      [6,7,8,9,10]
    ])

mtx6 = np.array([
      [11,12,13,14,15],
      [16,17,18,19,20]
    ])

print(mtx5)
print()
print(mtx6)
print()

print("After concatecate")
d = np.concatenate((mtx5,mtx6), axis=0)
e = np.concatenate((mtx5,mtx6), axis=1)

print("When axis: 0 (new row add)")
print(d)

print("\nWhen axis: 1 (new column add)")
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12 13 14 15]
 [16 17 18 19 20]]

After concatecate
When axis: 0 (new row add)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

When axis: 1 (new column add)
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


# 3.3 join using Stack (another way)

In [25]:
mtx7 = np.array([1,2,3,4,5],)
mtx8 = np.array([6,7,8,9,10])

f = np.stack((mtx7,mtx8), axis=1)

# i can use v,w,d instead od axis
h = np.hstack((mtx7,mtx8))
v = np.vstack((mtx7,mtx8))
d = np.dstack((mtx7,mtx8))

print(f"This is from  f \n{f}")
print()
print(f"This is from  h \n{h}")
print()
print(f"This is from  v \n{v}")
print()
print(f"This is from  d \n{d}")

This is from  f 
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]

This is from  h 
[ 1  2  3  4  5  6  7  8  9 10]

This is from  v 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

This is from  d 
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


# 4. Split

#4.1 1-D array

In [28]:
mtx9 = np.array([1,2,3,4,5,6,7,8,9,10])

i = np.array_split(mtx9, 3)

print(i)
print(type(i), type(i[0]))

print(i[0])

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
<class 'list'> <class 'numpy.ndarray'>
[1 2 3 4]


# 4.2 2-D array

In [35]:
mtx10 = np.array([
      [1,2,3,4,5],
      [6,7,8,9,10]
    ])
print(f"Original array:\n{mtx10}")
print()

j = np.array_split(mtx10, 3, axis=0)
k = np.array_split(mtx10, 3, axis=1)

print(f"Split array axix 0:\n{j}")
print()
print(f"Split array axix 1:\n{k}")
print()

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Split array axix 0:
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([], shape=(0, 5), dtype=int64)]

Split array axix 1:
[array([[1, 2],
       [6, 7]]), array([[3, 4],
       [8, 9]]), array([[ 5],
       [10]])]

