# Import Libraries

- **Reference Notebook:** [colab.research.google.com](https://colab.research.google.com/drive/1022HrY0cW-DNMj3vG2n6-OjmRXtE8lh2?usp=sharing)

In [56]:
import torch
import torch.nn as nn

# Custom Gradient

In [57]:
# y = x^2
def dx_dy(x: int):
  return 2*x

dx_dy(2) # 2x

4

# Using `PyTorch Grad`

In [58]:
# Make X
x = torch.tensor(2.0, requires_grad=True)
print(f'x = {x}')
display(x)

# Calculate Y
y = x**2
print(f'\ny = {y}')
display(y)

# Calculate Gradient
y.backward()

# Print Gradient
print(f'\nPrint Gradient')
x.grad

x = 2.0


tensor(2., requires_grad=True)


y = 4.0


tensor(4., grad_fn=<PowBackward0>)


Print Gradient


tensor(4.)

# Make a small neural network

## Input Init

In [59]:
x = torch.rand(size=(3, 2), dtype=torch.float32)
y = torch.randint(size=(3, 1), high=2, low=0, dtype=torch.int32)

display(x)
display(y)

tensor([[0.7568, 0.4987],
        [0.1407, 0.2195],
        [0.0798, 0.2837]])

tensor([[0],
        [1],
        [0]], dtype=torch.int32)

## Weight Init

In [60]:
w = torch.rand(size=(1, 2), requires_grad=True)
b = torch.rand(size=(1, 1), requires_grad=True)

w_prev = w.clone()
b_prev = b.clone()

display(w)
display(b)

tensor([[0.7951, 0.2231]], requires_grad=True)

tensor([[0.7507]], requires_grad=True)

## Training

In [61]:
# z = x @ w.T + b
z = torch.matmul(x, w.T) + b
y_pred = torch.sigmoid(z)
y_pred

tensor([[0.8121],
        [0.7133],
        [0.7063]], grad_fn=<SigmoidBackward0>)

## Loss Calculate

In [62]:
bce_loss = nn.BCELoss()
loss = bce_loss(y_pred, y.float())
loss

tensor(1.0783, grad_fn=<BinaryCrossEntropyBackward0>)

## Backpropagation

In [63]:
loss.backward()

print("Backword")
w.grad

Backword


tensor([[0.2102, 0.1808]])

In [64]:
print(f'Previous weights: {w_prev}')
print(f'Backword Weights: {w.grad}')

print(f'Previous bias: {b_prev}')
print(f'Backword bias: {b.grad}')

Previous weights: tensor([[0.7951, 0.2231]], grad_fn=<CloneBackward0>)
Backword Weights: tensor([[0.2102, 0.1808]])
Previous bias: tensor([[0.7507]], grad_fn=<CloneBackward0>)
Backword bias: tensor([[0.4106]])


## Clean Gradient

In [65]:
display(w.grad.zero_())
display(b.grad.zero_())

tensor([[0., 0.]])

tensor([[0.]])

# Vector Gradient

In [68]:
v = torch.tensor([4., 2., 6.,], requires_grad=True)
v

tensor([4., 2., 6.], requires_grad=True)

In [69]:
y = (v**2).mean()
display(y)

y.backward()

display(v.grad)

tensor(18.6667, grad_fn=<MeanBackward0>)

tensor([2.6667, 1.3333, 4.0000])

# Disable Gradient

- option 1 - `requires_grad_(False)`
- option 2 - `detach()`
- option 3 - `torch.no_grad()`

In [83]:
x = torch.rand(size=(1, 4), requires_grad=True)
display(x)

y = x**2
z = torch.sigmoid(y)
zp = z.mean()
display('Loss', zp)

# Backword
zp.backward()
display('Backowrd Value: ', x.grad)

tensor([[0.1164, 0.1507, 0.0669, 0.7536]], requires_grad=True)

'Loss'

tensor(0.5371, grad_fn=<MeanBackward0>)

'Backowrd Value: '

tensor([[0.0145, 0.0188, 0.0084, 0.0870]])

## option 1 - `requires_grad_(False)`

In [78]:
x.requires_grad_(False)

# zp.grad

tensor([[0.4396, 0.0896, 0.2695, 0.1721]])

In [ ]:
y = (x**2).mean()
y.backward() # Give an Error

## `detach()`

In [81]:
z = x.detach()
z

tensor([[0.9050, 0.3121, 0.1193, 0.6822]])

In [ ]:
y = (z**2).mean()
y.backward() # Give an Error

## `torch.no_grad()`

In [87]:
with torch.no_grad():
  y = (x**2).mean()
  print(y)

tensor(0.1522)


In [88]:
y = (x**2).mean()
print(y)

tensor(0.1522, grad_fn=<MeanBackward0>)
