# Import Library

In [1]:
import torch

In [2]:
# Torch Version
torch.__version__

'2.9.0+cu126'

# Check Device

In [3]:
if torch.cuda.is_available():
  print('GPU Available')
  print('GPU Model: ', torch.cuda.get_device_name(device=0))
else:
  print('GPU is not Available')



GPU is not Available


# Tensors

## Creating Tensors

In [4]:
# Empty Tensors
torch.empty(3, 4) # Empty value

tensor([[4.2747e-33, 0.0000e+00, 2.9848e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4653e+30, 1.8788e+31, 1.7220e+22]])

In [5]:
# Type Check
type(torch.empty(2, 3))

torch.Tensor

In [6]:
# Zeros
torch.zeros(3, 4) # all are zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# Ones
torch.ones(3, 4) # all are one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# rand
torch.rand(3, 4) # all value are from 0 -> 1

tensor([[0.3067, 0.0993, 0.9256, 0.1887],
        [0.7323, 0.4157, 0.2849, 0.6749],
        [0.3603, 0.1891, 0.3504, 0.9862]])

In [9]:
# manual seed function
torch.manual_seed(100)
torch.rand(3, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [10]:
# manual seed function
torch.manual_seed(100)
torch.rand(3, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [11]:
# Using Tensor
torch.tensor([[1, 2, 3],[4,5,6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
# Arange Tensor
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [13]:
# Linespace Tensors
torch.linspace(0, 10, 12, dtype=torch.float16)

tensor([ 0.0000,  0.9092,  1.8184,  2.7266,  3.6367,  4.5469,  5.4531,  6.3633,
         7.2734,  8.1797,  9.0938, 10.0000], dtype=torch.float16)

In [14]:
# Eye Tensor
torch.eye(4, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [15]:
# Full
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensor-Shape

In [16]:
a = torch.rand(3, 4, dtype=torch.float32)
a

tensor([[0.7118, 0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557, 0.9770]])

In [17]:
a.shape

torch.Size([3, 4])

## New Tensor same as Existing `X`

In [18]:
# Zeros tensor same as a
torch.zeros_like(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Ones tensor same as a
# The line 'a.dtype = torch.int32' causes an AttributeError because a tensor's dtype cannot be directly assigned.
# To create a new tensor of ones with the same shape as 'a' and a specific dtype, use 'torch.ones_like()'.
torch.ones_like(a, dtype=torch.int32)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

# Tensor Data type

In [20]:
torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical operations

In [21]:
x = torch.rand(2, 2)
x

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])

In [22]:
# Addition
x+2

tensor([[2.4440, 2.9478],
        [2.7445, 2.4892]])

In [23]:
# Subtraction
x-2

tensor([[-1.5560, -1.0522],
        [-1.2555, -1.5108]])

In [24]:
# Multiplication
x*2

tensor([[0.8880, 1.8957],
        [1.4890, 0.9784]])

In [25]:
# Division
x/2

tensor([[0.2220, 0.4739],
        [0.3722, 0.2446]])

In [26]:
# Int Devision
x*100//2

tensor([[22., 47.],
        [37., 24.]])

In [27]:
# mod
((x * 100)//3)%2

tensor([[0., 1.],
        [0., 0.]])

In [28]:
# power
x**2

tensor([[0.1972, 0.8984],
        [0.5543, 0.2393]])

## Element wise operation

In [29]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)

display(a)
display(b)

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])

tensor([[0.7909, 0.4235],
        [0.0169, 0.2209]])

In [30]:
# Addition
a+b

tensor([[1.0334, 1.1238],
        [0.5446, 0.4681]])

In [31]:
# Subtraction
a-b

tensor([[-0.5483,  0.2769],
        [ 0.5108,  0.0263]])

In [32]:
# Division
a/b

tensor([[ 0.3067,  1.6537],
        [31.2257,  1.1190]])

In [33]:
# multiplication
a*b

tensor([[0.1918, 0.2966],
        [0.0089, 0.0546]])

In [34]:
# power
a**b

tensor([[0.3262, 0.8600],
        [0.9893, 0.7344]])

In [35]:
# mode
a%b

tensor([[0.2426, 0.2769],
        [0.0038, 0.0263]])

In [36]:
x = torch.tensor([-1.9, -2.5, 2.51, 4.0])
x

tensor([-1.9000, -2.5000,  2.5100,  4.0000])

In [37]:
# absoulate
torch.abs(x)

tensor([1.9000, 2.5000, 2.5100, 4.0000])

In [38]:
# negative (-1*x)
torch.neg(x)

tensor([ 1.9000,  2.5000, -2.5100, -4.0000])

In [39]:
# round
torch.round(x)

tensor([-2., -2.,  3.,  4.])

In [40]:
# ceil value
torch.ceil(x)

tensor([-1., -2.,  3.,  4.])

In [41]:
# Floor Value
torch.floor(x)

tensor([-2., -3.,  2.,  4.])

In [44]:
# Clamp
display(x)
torch.clamp(x, min=3, max=5)

tensor([-1.9000, -2.5000,  2.5100,  4.0000])

tensor([3., 3., 3., 4.])

## Reduction Operation

In [46]:
x = torch.randint(size=(2, 3), low=3, high=7, dtype=torch.float32)
x

tensor([[6., 6., 4.],
        [6., 4., 4.]])

In [50]:
# sum
display(torch.sum(x))

# Sum among columns
display(torch.sum(x, dim=0, dtype=torch.float16))

# Sum among row
display(torch.sum(x, dim=1, dtype=torch.torch.float16))

tensor(30.)

tensor([12., 10.,  8.], dtype=torch.float16)

tensor([16., 14.], dtype=torch.float16)

In [51]:
# Mean
display(torch.mean(x))

# mean among columns
display(torch.mean(x, dim=0, dtype=torch.float16))

# mean among row
display(torch.mean(x, dim=1, dtype=torch.float16))

tensor(5.)

tensor([6., 5., 4.], dtype=torch.float16)

tensor([5.3320, 4.6680], dtype=torch.float16)

In [54]:
# Median
display(torch.median(x))

tensor(4.)

In [56]:
# input tensor
display(x)

# max element
display(torch.max(x))

# mean element
display(torch.min(x))

tensor([[6., 6., 4.],
        [6., 4., 4.]])

tensor(6.)

tensor(4.)

In [59]:
# Product
display(6*6*4*6*4*4)

# torch Product
torch.prod(x)

13824

tensor(13824.)

In [60]:
# Std deviation
torch.std(x)

tensor(1.0954)

In [61]:
# variance
torch.var(x)

tensor(1.2000)

In [62]:
# argmax
torch.argmax(x)

tensor(0)

In [63]:
# argmin
torch.argmin(x)

tensor(2)

## Matrix Operations

In [64]:
a = torch.randint(size=(2, 3), low=0, high=20, dtype=torch.int16)
b = torch.randint(size=(3, 2), low=20, high=30, dtype=torch.int16)

display(a)
display(b)

tensor([[18, 19,  7],
        [19, 12,  6]], dtype=torch.int16)

tensor([[27, 27],
        [28, 23],
        [26, 21]], dtype=torch.int16)

In [68]:
# shape of a and b
display(a.shape, b.shape)

print()
# Multiplication
torch.matmul(a, b)

torch.Size([2, 3])

torch.Size([3, 2])

tensor([[1200, 1070],
        [1005,  915]], dtype=torch.int16)

In [71]:
print("Matrix A")
display(a)

print()
# transpose
a.T

Matrix A


tensor([[18, 19,  7],
        [19, 12,  6]], dtype=torch.int16)

tensor([[18, 19],
        [19, 12],
        [ 7,  6]], dtype=torch.int16)

In [77]:
c = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
display(c)

print()
#Determining
torch.det(c)

tensor([[2., 7., 1.],
        [1., 5., 4.],
        [4., 1., 1.]])

tensor(88.0000)

In [78]:
# inverse
torch.inverse(c)

tensor([[ 0.0114, -0.0682,  0.2614],
        [ 0.1705, -0.0227, -0.0795],
        [-0.2159,  0.2955,  0.0341]])

In [79]:
v1 = torch.tensor([2, 3, 4])
v2 = torch.tensor([5, 6, 7])

torch.dot(v1, v2)

tensor(56)

## Comparison operations

In [80]:
i = torch.randint(size=(3, 3), low=1, high=10)
j = torch.randint(size=(3, 3), low=1, high=10)

display(i)
display(j)

tensor([[2, 1, 8],
        [6, 7, 2],
        [1, 7, 4]])

tensor([[1, 2, 8],
        [2, 2, 4],
        [4, 8, 6]])

In [84]:
# These equations are basically pointwise operator

# equal
print('Equal:')
display(i == j)

# not equal
print('\nNot Equal:')
display(i != j)

# less than
print('\na Less Than b:')
display(i < j)

# less than
print('\na Greater Than b:')
display(i > j)

Equal:


tensor([[False, False,  True],
        [False, False, False],
        [False, False, False]])


Not Equal:


tensor([[ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True]])


a Less Than b:


tensor([[False,  True, False],
        [False, False,  True],
        [ True,  True,  True]])


a Greater Than b:


tensor([[ True, False, False],
        [ True,  True, False],
        [False, False, False]])

## Special functions

In [94]:
k = torch.randint(size=(2, 3), low=-10, high=10, dtype=torch.float32)
k

tensor([[ 2.,  7.,  0.],
        [-8.,  4.,  4.]])

In [95]:
# log
torch.log(k)

tensor([[0.6931, 1.9459,   -inf],
        [   nan, 1.3863, 1.3863]])

In [96]:
# exp
torch.exp(k)

tensor([[7.3891e+00, 1.0966e+03, 1.0000e+00],
        [3.3546e-04, 5.4598e+01, 5.4598e+01]])

In [97]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 2.6458, 0.0000],
        [   nan, 2.0000, 2.0000]])

In [98]:
# sigmoid
torch.sigmoid(k)

tensor([[8.8080e-01, 9.9909e-01, 5.0000e-01],
        [3.3535e-04, 9.8201e-01, 9.8201e-01]])

In [99]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.9995e-01, 9.5257e-01, 1.7986e-02],
        [4.5398e-05, 4.7426e-02, 9.8201e-01]])

In [100]:
# relu
torch.relu(k)

tensor([[2., 7., 0.],
        [0., 4., 4.]])

# Inplace Operations

In [111]:
a = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
b = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)

display(a)
print()
display(b)

tensor([[0., 2., 5.],
        [2., 8., 0.],
        [2., 5., 3.]])

tensor([[6., 7., 8.],
        [1., 2., 3.],
        [2., 7., 9.]])

In [112]:
# arithmatic add
a.add_(b)

tensor([[ 6.,  9., 13.],
        [ 3., 10.,  3.],
        [ 4., 12., 12.]])

In [113]:
a

tensor([[ 6.,  9., 13.],
        [ 3., 10.,  3.],
        [ 4., 12., 12.]])

In [114]:
a.sigmoid_()

tensor([[0.9975, 0.9999, 1.0000],
        [0.9526, 1.0000, 0.9526],
        [0.9820, 1.0000, 1.0000]])

In [115]:
a

tensor([[0.9975, 0.9999, 1.0000],
        [0.9526, 1.0000, 0.9526],
        [0.9820, 1.0000, 1.0000]])

# Copying a Tensor

In [117]:
cx = torch.rand(2, 2)
cx

tensor([[0.1953, 0.9991],
        [0.1133, 0.0135]])

In [118]:
dx = cx.clone()
dx

tensor([[0.1953, 0.9991],
        [0.1133, 0.0135]])